services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    command: ["--auth"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./startup-scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - prod
    env_file:
      - .env

  backend:
    build: backend
    container_name: print-backend
    restart: always
    ports:
      - "8001:80"
    depends_on:
      - mongo
    networks:
      - prod
    env_file:
      - .env

  frontend:
    build: frontend
    container_name: print-frontend
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - prod

volumes:
  mongo_data:
networks:
  prod:
