services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - prod
<<<<<<< HEAD
=======
    env_file:
      - .env
>>>>>>> dev

  backend:
    build: backend
    container_name: print-backend
    restart: always
    ports:
      - "8001:5000"
    depends_on:
      - mongo
    networks:
      - prod
<<<<<<< HEAD
=======
    env_file:
      - .env
>>>>>>> dev

  frontend:
    build: frontend
    container_name: print-frontend
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - prod

volumes:
  mongo_data:
networks:
  prod:
