services:

  mongo-dev:
    image: mongo:6
    container_name: mongo-dev
    restart: always
    command: ["--auth"]
    ports:
      - "27018:27017"
    volumes:
      - mongo_data_dev:/data/db
      - ./startup-scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - dev
    env_file:
      - .env.dev

  backend-dev:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    container_name: print-backend-dev
    restart: always
    ports:
      - "8003:80"
    depends_on:
      - mongo-dev
    networks:
      - dev
    env_file:
      - .env.dev

  frontend-dev:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    container_name: print-frontend-dev
    restart: always
    ports:
      - "8002:80"
    depends_on:
      - backend-dev
    networks:
      - dev

volumes:
  mongo_data_dev:
networks:
  dev:
